from typing import Any, List

from app.db.core.repository import Repository


class Store:
    def __init__(self, db_uri: str, *repositories: Repository) -> None: ...
    def connect(self) -> Any: ...
    def disconnect(self): ...
    def database(self) -> Any: ...
